#!/bin/bash
# Script to update documents in the collection school

# Check if the database name is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <database_name>"
    exit 1
fi

# Connect to MongoDB and update documents in the school collection
mongo "$1" --quiet --eval 'db.school.update({ name: "Holberton school" }, { $set: { address: "972 Mission street" } }, { multi: true });'
